version: '2'
services:
  plantycompareportal-mongodb:
    image: mongo:4.0.9
    ports:
      - '27017:27017'
    command: mongos --configdb plantycompareportal-mongodb-config
  plantycompareportal-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  plantycompareportal-mongodb-config:
    image: mongo:4.0.9
    container_name: plantycompareportal-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
